In [1]:
# basic ndarray class
import numpy as np
vec1 = np.array([1,1])
vec2 = np.array([0,2])
print vec1, '*', vec2, '=', vec1*vec2
print vec1, '+', vec2, '=', vec1+vec2



[1 1] * [0 2] = [0 2]
[1 1] + [0 2] = [1 3]


In [20]:
#shape and size
A = np.array([ [1,0], [0,2] ])
print A.ndim, A.shape, A.size, A.dtype

B = A.reshape([1,4])
print B
A.reshape([1,4])
print A,'after reshape is\n', A


A = np.array([ [1,0], [0,2] ])
print A,'after resize is',
A.resize([1,4])
print A

2 (2, 2) 4 int64
[[1 0 0 2]]
[[1 0]
 [0 2]] after reshape is
[[1 0]
 [0 2]]
[[1 0]
 [0 2]] after resize is [[1 0 0 2]]


In [24]:
#create
mat3_4 = np.zeros([3,4])
print mat3_4

mat3_4[0][0]=1
print mat3_4

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [47]:
#random
np.random.seed(1)
a = np.random.random((2,2)) #uniform(0,1)
print a
a = np.random.randint(1,3,(2,2))
print a
b = np.array((1,3))
print b
c = np.dot(a,b)
print c
#other random

[[  4.17022005e-01   7.20324493e-01]
 [  1.14374817e-04   3.02332573e-01]]
[[2 1]
 [1 2]]
[1 3]
[5 7]


In [48]:
print np.linspace(0,1,11)  #uniformly interpolate 

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [50]:
print c.sum()
print c.sum(axi)

12
